##################################################
# RFNoC Sources
##################################################

RFNOC_SRCS += $(addprefix $(RFNOC_OOTEXAMPLE_DIR)/fpga-src/, \
noc_block_complextomagphase.v \
noc_block_addsuboot.v \
)
